<a href="https://colab.research.google.com/github/ajay152603/Python-for-DS/blob/master/1.%20UnderstandPythonLibraries%20%20-Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#** Basic understand of python libraries**  numpy

# Numpy


> this libarary is basically used with scalar, vector,array(can be more than 3 dimentions..etc


> In short working with numbers





In [0]:
#importing numpy
import numpy as np

In [0]:
#list of array
# a =np.array([[1,2,3], [2,4,7]])
# print(a)
# print(type(a))

In [0]:
# metrix of complex numbers
# b = np.array( [[1,2,3],[2,3,4]], dtype = complex)
# print(b)

In [0]:
#create a array which compaises of zeros
a = np.zeros((3,2) , dtype = int)
print( 'a = {}'.format(a))

a = [[0 0]
 [0 0]
 [0 0]]


In [0]:
# # # create an array of ones
# a = np.ones((2,2,3), dtype = np.int16)
# print ('a ={}'.format(a)) 


In [0]:
#create an empty array
a = np.empty((2,4))
print ('a= {}'.format(a))


a= [[2.80708654e-316 1.58101007e-322 2.07955588e-312 4.26007226e+174]
 [4.79820217e+174 1.59991648e+160 2.61846957e+180 1.33511316e-306]]


In [0]:
# #Create a identity array
a= np.eye((2),dtype = np.int16)
print ('a= {}'.format(a))


a= [[1 0]
 [0 1]]


In [0]:
# # create an array of ones with the same size of array (same as eg 14)

# b = np.ones_like(a)
# print('b = {}'.format(b))

In [0]:
# # create an array filled with inf values
# b = np.full((3,6), np.inf)
# print('b = {}'.format(b))


In [0]:
# create a 3*3 array
# c = np.array( [ [1,2,3],[7,3,4],[1,8,5]],  np.int16)
# print ( 'c ={}'.format(c))

In [0]:
# find diagonal of previous array

# d= np.diag(c)
# print ( 'd ={}'.format(d))


In [0]:
# #find the diagonals above and below the main diagonal
# e= np.diag(c, k=1)
# print ('this  elements are above the diagonal elements ::' + ' '+ 'e ={}'.format(e))

# f= np.diag(c, k=-1)
# print ('these are the elements below diagonal ::' +'  ' + 'f ={}'.format(f))

# 3. Create a sequence of numbers

In [0]:
# # create a sequence of three numbers between 1 and 7

# a  = np.arange(1,7,3)
# print ('a ={}'.format(a))

In [0]:
# create a sequence of numbers between 1 and 7 with stride 0.5

# a  = np.arange(1,7,.5)
# print ('a ={}'.format(a))

In [0]:
# create 10 numbers between 1 and 7
# a  = np.linspace(1,7,10)
# b = np.around(a)
# print ('b ={}'.format(b))

# Reshape an array

In [0]:
# create a vector of 10 elements and reshape it into 5*2 array
# a = np.arange(10)
# print (a)
# print ("-"*20)
# b = a.reshape(5,2)
# print(b)

In [0]:
# c =b.flatten()
# print ('c = {}'.format(c))
# c.shape

In [0]:
# create a 2*3 array then find its transpose

# a= np.arange(6)
# print(a)
# print ("-"*30)
# b= a.reshape(2,3)
# print(b)
# print ("-"*30)
# c= b.transpose()
# print (c)

In [0]:
# create a random 3*2 array 
# a= np.random.random_sample((2,3))*5 +3

# print(a)

[[6.48961636 7.44073888 5.22169097]
 [7.91199263 4.61287223 7.9906901 ]]


In [0]:
# find the minimum of the previous array (a) and its index
# print('min(a) = {}'.format(np.min(a)))
# print('minposition(a) ={}'.format(np.argmax(a)))
# print ("-"*30)
# print('max(a) = {}'.format(np.max(a)))
# print('maxposition(a) ={}'.format(np.argmax(a)))


min(a) = 4.612872233879607
minposition(a) =5
------------------------------
max(a) = 7.990690099819349
maxposition(a) =5


In [0]:
print ("b holds the value of max of row 1 and row 2 = {}".format(np.maximum(a[0],a[1])))

b holds the value of max of row 1 and row 2 = [7.91199263 7.44073888 7.9906901 ]


# Statistical measures

In [0]:
 # generate a random 3*2 array and compute its mean, variance, and standard deviation
#  a= np.random.random_sample((3,2)) *5
#  print (" this is the required array = \n \n {}".format(a))
#  print("-" * 30)
#  print("mean = \n \n{}".format(np.mean(a)))
#  print("-" * 30)
#  print("meadian = \n \n{}".format( np.median(a)))
#  print("-" * 30)
#  print("Standard Deviation = \n \n{}".format(np.std(a) ))
#  print("-" * 30)
#  print("Varience = \n \n{}".format(np.var(a) ))


 this is the required array = 
 
 [[4.81140325 1.07952759]
 [2.7656584  4.90064821]
 [1.75529894 4.05421231]]
------------------------------
mean = 
 
3.227791447677593
------------------------------
meadian = 
 
3.409935352196607
------------------------------
Standard Deviation = 
 
1.4711722218106773
------------------------------
Varience = 
 
2.164347706227365


# Linear Algebra

In [0]:
# create a square, random matrix a and find its exponential
# a= np.random.random_sample ((3,3))
# print ("martix = \n \n {}".format(a))
# print ("-"*30)
# print("exp of matrix  = \n \n {}".format(np.exp(a)))


martix = 
 
 [[0.70564228 0.7876283  0.39730505]
 [0.03606375 0.91439312 0.08089569]
 [0.43379212 0.21281596 0.18199714]]
------------------------------
exp of matrix  = 
 
 [[2.02514698 2.19817682 1.48780972]
 [1.03672193 2.49526047 1.08425779]
 [1.54309805 1.23715694 1.19961077]]


In [0]:
# compute the determinant, rank, and trace of b
# print("exp of matrix  = \n \n {}".format(np.linalg.det(a)))
# print ("-"*30)
# print("rank of matrix  = \n \n {}".format(np.linalg.matrix_rank(a)))
# print ("-"*30)
# print("trace of matrix  = \n \n {}".format(np.trace(a)))


exp of matrix  = 
 
 -0.026791998686123347
------------------------------
rank of matrix  = 
 
 3
------------------------------
trace of matrix  = 
 
 1.8020325482204291


In [0]:
#find the eigen values and the eigen vectors of matrix 
#print("eigen value of matrix  = \n \n {}".format(np.linalg.eigvals(a)))
# print ("-"*30)
# eigen_value, eigen_vector = np.linalg.eig(a)

# print("eigen value of matrix  = \n \n {}".format(eigen_value))
# print ("-"*30)
# print("eigen vector of matrix  = \n \n {}".format(eigen_vector))


------------------------------
eigen value of matrix  = 
 
 [-0.03413895  1.15910179  0.67706971]
------------------------------
eigen vector of matrix  = 
 
 [[ 0.42091571 -0.85635316  0.77739181]
 [ 0.06118249 -0.27142849 -0.30554823]
 [-0.90503407 -0.43930153  0.54982021]]


In [0]:
# implement singular value decomposition on matrix b
# u,s,vh = np.linalg.svd(a)
# print("U of b is :\n \n {}".format(u))
# print ("-"*30)
# print("V of b is :\n \n {}".format(vh))
# print ("-"*30)
# print("singular values of b are :\n \n {}".format(s))

U of b is :
 
 [[-0.7731413   0.38577287 -0.50342013]
 [-0.55523214 -0.79532808  0.2432499 ]
 [-0.30654495  0.46758158  0.82909448]]
------------------------------
V of b is :
 
 [[-0.48775292 -0.82522182 -0.28479121]
 [ 0.77185888 -0.56006634  0.30093116]
 [ 0.40783693  0.07303857 -0.91012878]]
------------------------------
singular values of b are :
 
 [1.43220409 0.57830305 0.0323478 ]


In [0]:
# generate two arrays and compute their dot product
# a = np.array([[1,2],[3,4]]) 
# b = np.array([[11,12],[13,14]]) 
# c = np.dot(a,b)
# print("the dot product of a and b is:\n{}".format(c))
# d = np.matmul(a,b)
# print("the dot product of a and b is:\n{}".format(d))
# print("the dot product of a and b is:\n{}".format(a*b))

the dot product of a and b is:
[[37 40]
 [85 92]]
the dot product of a and b is:
[[37 40]
 [85 92]]
the dot product of a and b is:
[[11 24]
 [39 56]]


In [0]:
# # Generate an array and compute its inverse and its pseudo inverse
# a = np.random.random_sample((3,3))
# print(a)
# # Compute the (multiplicative) inverse of a matrix.
# print("the inverse of a is:")
# b = np.linalg.inv(a)
# print(b)
# #compute the (Moore-Penrose) pseudo-inverse of a
# print("the pseudo-inverse of a is:")
# c = np.linalg.pinv(a)
# print(c)

import random
np.random.seed(3)
d = random.randint(1, 10)  
print(d)
print ("-"*30)
np.random.seed(5)
d = random.randint(1, 10) 
print(d)




6
------------------------------
9
