<a href="https://colab.research.google.com/github/ajay152603/Python-for-DS/blob/master/Assignment_1_DS_Practicefor%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [0]:
import numpy as np


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [0]:
c= np.arange(100)
print ('c = {}'.format(c))

print("-"*30)

d = np.zeros((3,3), dtype =int)
print (' d is martix of type int and size (3*3)= \n \n {} '.format(d))




c = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
------------------------------
 d is martix of type int and size (3*3)= 
 
 [[0 0 0]
 [0 0 0]
 [0 0 0]] 


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [0]:
e = [[1,2,3],[4,5,6],[7,8,9]]

e = np.array(e)
print ('e = \n \n {}'.format(e))






e = 
 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [0]:
f = np.ones((5,5) , dtype = np.int16)
print ('f = \n \n {}'.format(f))
print("-"*30)
g = np.eye(5,5) 
print ('g = \n \n {}'.format(g))
print("-"*30)


f = 
 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
------------------------------
g = 
 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
------------------------------


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [0]:
h = c.reshape (10,10)

print ('h = \n \n {}'.format(h))
print("-"*30)

g = h.flatten()

print ("c′ = \n \n {}".format(g))
print("-"*30)

i = c.shape
print (i)
j = g.shape
print(j)
print("-"*30)

if c.shape == g.shape:
  print("yes")
else:
  print("No")  



h = 
 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
------------------------------
c′ = 
 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
------------------------------
(100,)
(100,)
------------------------------
yes


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [0]:
A = np.random.rand(2,10,5)
print("-"*30)
b = np.transpose (A)
c= b.reshape(5,2,10)
print ("A′ = \n \n {}".format(c))
print("-"*30)



------------------------------
A′ = 
 
 [[[0.69983364 0.23503338 0.16849256 0.81256358 0.35370792 0.05049852
   0.39640196 0.48830008 0.00264928 0.78468611]
  [0.90883772 0.09748689 0.79972199 0.38269273 0.77071668 0.08062032
   0.608764   0.9019124  0.64733119 0.21343662]]

 [[0.53613986 0.35529581 0.47304198 0.05887146 0.59527993 0.25568487
   0.64023775 0.39907028 0.33158396 0.29096289]
  [0.37954248 0.8926549  0.9927908  0.36191051 0.91578983 0.00209909
   0.65165973 0.4275005  0.05737021 0.86426231]]

 [[0.19691245 0.27730886 0.58752743 0.73040165 0.91252431 0.81037524
   0.33674741 0.52925726 0.98806374 0.3401883 ]
  [0.16525272 0.69992582 0.35981761 0.58954298 0.83005644 0.41747477
   0.43394643 0.65730611 0.02000012 0.35953205]]

 [[0.23936046 0.93211764 0.34938987 0.25266238 0.01696337 0.00359659
   0.68894001 0.17467452 0.61004711 0.15187097]
  [0.96489009 0.40486553 0.69067352 0.10837109 0.32902783 0.85622381
   0.51558721 0.9649745  0.23830445 0.28887629]]

 [[0.10261296 0.

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [55]:
np.random.seed(0)
X = np.random.rand(10,5)
print (X)
print("-"*30)
print ("X holds the value of min row wise= {}".format(np.minimum(X[0],X[1])))
print("-"*30)
print ("X holds the value of max row wise= {}".format(np.maximum(X[0],X[1])))
print("-"*30)

print ("X holds the value of min column wise = {}".format(np.amin(X, axis=0)))
print("-"*30)
print ("X holds the value of max  column wise = {}".format(np.amax(X, axis= 0)))
print("-"*30)

print ("X holds the value of min of entire matix= {}".format(np.min(X)))
print("-"*30)
print ("X holds the value of minposition = {}".format(np.argmin(X)))
print("-"*30)

print ("X holds the value of max  of entire matix = {}".format(np.max(X)))
print("-"*30)
print ("X holds the value of maxposition= {}".format(np.argmax(X)))
print("-"*30)




[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]]
------------------------------
X holds the value of min row wise= [0.5488135  0.43758721 0.60276338 0.54488318 0.38344152]
------------------------------
X holds the value of max row wise= [0.64589411 0.71518937 0.891773   0.96366276 0.4236548 ]
------------------------------
X holds the value of min column wise = [0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ]
------------------------------
X holds the val

Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [64]:
np.random.seed(0)
X = np.random.rand(10,5)
print (X)
print("-"*30)
print ("mean column wise= \n \n {}".format( np.mean(X, axis = 0)))
print("-"*30)
print ("mean row wise = \n \n {}".format( np.mean(X,  axis = 1)))
print("-"*30)
print ("mean = \n \n {}".format( np.mean(X)))
print("-"*30)
print ("std column wise= \n \n {}".format( np.std(X, axis = 0)))
print("-"*30)
print ("std row wise= \n \n {}".format( np.std(X,  axis = 1)))
print("-"*30)
print ("std  = \n \n {}".format( np.std(X)))


[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]]
------------------------------
mean column wise= 
 
 [0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
------------------------------
mean row wise = 
 
 [0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717]
------------------------------
mean = 
 
 0.5379651182755409
------------------------------
std column wise= 
 
 [0.24687647 0.25752158 0.22948615

Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [67]:
np.random.seed(3)
Y = np.random.rand(10,10)
#print (Y)
print("-"*30)
print ("Det  = \n \n {}".format( np.linalg.det(Y)))
print("-"*30)
print ("Rank  = \n \n {}".format( np.linalg.Rank(Y)))
print("-"*30)
print ("Diag  = \n \n {}".format( np.diag(Y)))
print("-"*30)
print ("Trace  = \n \n {}".format( np.trace(Y)))
print("-"*30)
print ("Eig Val  = \n \n {}".format( np.linalg.eigvals(Y)))
print("-"*30)
print ("Ivn  = \n \n {}".format( np.linalg.inv (Y)))
print("-"*30)
print ("Ivn  = \n \n {}".format( np.linalg.pinv (Y)))







[[0.5507979  0.70814782 0.29090474 0.51082761 0.89294695 0.89629309
  0.12558531 0.20724288 0.0514672  0.44080984]
 [0.02987621 0.45683322 0.64914405 0.27848728 0.6762549  0.59086282
  0.02398188 0.55885409 0.25925245 0.4151012 ]
 [0.28352508 0.69313792 0.44045372 0.15686774 0.54464902 0.78031476
  0.30636353 0.22195788 0.38797126 0.93638365]
 [0.97599542 0.67238368 0.90283411 0.84575087 0.37799404 0.09221701
  0.6534109  0.55784076 0.36156476 0.2250545 ]
 [0.40651992 0.46894025 0.26923558 0.29179277 0.4576864  0.86053391
  0.5862529  0.28348786 0.27797751 0.45462208]
 [0.20541034 0.20137871 0.51403506 0.08722937 0.48358553 0.36217621
  0.70768662 0.74674622 0.69109292 0.68918041]
 [0.37360012 0.6681348  0.33984866 0.57279387 0.32580716 0.44514505
  0.06152893 0.24267542 0.97160261 0.2305842 ]
 [0.69147751 0.65047686 0.72393914 0.47508861 0.59666377 0.06696942
  0.07256214 0.19897603 0.151861   0.10010434]
 [0.12929386 0.55327773 0.18781482 0.95210124 0.68161178 0.54101967
  0.7071806 

AttributeError: ignored

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt


Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [0]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"



### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---





---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.