<a href="https://colab.research.google.com/github/ajay152603/Python-for-DS/blob/master/UnderstandPythonLibraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#** Basic understand of python libraries** 

# Numpy


> this libarary is basically used with scalar, vector,array(can be more than 3 dimentions..etc


> In short working with numbers





In [0]:
#importing numpy
import numpy as np

In [0]:
#list of array
# a =np.array([[1,2,3], [2,4,7]])
# print(a)
# print(type(a))

In [0]:
# metrix of complex numbers
# b = np.array( [[1,2,3],[2,3,4]], dtype = complex)
# print(b)

In [84]:
#create a array which compaises of zeros
a = np.zeros((3,2) , dtype = int)
print( 'a = {}'.format(a))

a = [[0 0]
 [0 0]
 [0 0]]


In [0]:
# # # create an array of ones
# a = np.ones((2,2,3), dtype = np.int16)
# print ('a ={}'.format(a)) 


In [85]:
#create an empty array
a = np.empty((2,4))
print ('a= {}'.format(a))


a= [[2.80708654e-316 1.58101007e-322 2.07955588e-312 4.26007226e+174]
 [4.79820217e+174 1.59991648e+160 2.61846957e+180 1.33511316e-306]]


In [86]:
# #Create a identity array
a= np.eye((2),dtype = np.int16)
print ('a= {}'.format(a))


a= [[1 0]
 [0 1]]


In [0]:
# # create an array of ones with the same size of array (same as eg 14)

# b = np.ones_like(a)
# print('b = {}'.format(b))

In [0]:
# # create an array filled with inf values
# b = np.full((3,6), np.inf)
# print('b = {}'.format(b))


In [0]:
# create a 3*3 array
# c = np.array( [ [1,2,3],[7,3,4],[1,8,5]],  np.int16)
# print ( 'c ={}'.format(c))

In [0]:
# find diagonal of previous array

# d= np.diag(c)
# print ( 'd ={}'.format(d))


In [0]:
# #find the diagonals above and below the main diagonal
# e= np.diag(c, k=1)
# print ('this  elements are above the diagonal elements ::' + ' '+ 'e ={}'.format(e))

# f= np.diag(c, k=-1)
# print ('these are the elements below diagonal ::' +'  ' + 'f ={}'.format(f))

# 3. Create a sequence of numbers

In [0]:
# # create a sequence of three numbers between 1 and 7

# a  = np.arange(1,7,3)
# print ('a ={}'.format(a))

In [0]:
# create a sequence of numbers between 1 and 7 with stride 0.5

# a  = np.arange(1,7,.5)
# print ('a ={}'.format(a))

In [0]:
# create 10 numbers between 1 and 7
# a  = np.linspace(1,7,10)
# b = np.around(a)
# print ('b ={}'.format(b))

# Reshape an array

In [0]:
# create a vector of 10 elements and reshape it into 5*2 array
# a = np.arange(10)
# print (a)
# print ("-"*20)
# b = a.reshape(5,2)
# print(b)

In [0]:
# c =b.flatten()
# print ('c = {}'.format(c))
# c.shape

In [0]:
# create a 2*3 array then find its transpose

# a= np.arange(6)
# print(a)
# print ("-"*30)
# b= a.reshape(2,3)
# print(b)
# print ("-"*30)
# c= b.transpose()
# print (c)

In [96]:
# create a random 3*2 array 
a= np.random.random_sample((2,3))*5 +3

print(a)

[[6.48961636 7.44073888 5.22169097]
 [7.91199263 4.61287223 7.9906901 ]]


In [102]:
# find the minimum of the previous array (a) and its index
print('min(a) = {}'.format(np.min(a)))
print('minposition(a) ={}'.format(np.argmax(a)))
print ("-"*30)
print('max(a) = {}'.format(np.max(a)))
print('maxposition(a) ={}'.format(np.argmax(a)))


min(a) = 4.612872233879607
minposition(a) =5
------------------------------
max(a) = 7.990690099819349
maxposition(a) =5


In [110]:
print ("b holds the value of max of row 1 and row 2 = {}".format(np.maximum(a[0],a[1])))

b holds the value of max of row 1 and row 2 = [7.91199263 7.44073888 7.9906901 ]


# Statistical measures

In [129]:
 # generate a random 3*2 array and compute its mean, variance, and standard deviation
 a= np.random.random_sample((3,2)) *5
 print (" this is the required array = \n \n {}".format(a))
 print("-" * 30)
 print("mean = \n \n{}".format(np.mean(a)))
 print("-" * 30)
 print("meadian = \n \n{}".format( np.median(a)))
 print("-" * 30)
 print("Standard Deviation = \n \n{}".format(np.std(a) ))
 print("-" * 30)
 print("Varience = \n \n{}".format(np.var(a) ))


 this is the required array = 
 
 [[4.81140325 1.07952759]
 [2.7656584  4.90064821]
 [1.75529894 4.05421231]]
------------------------------
mean = 
 
3.227791447677593
------------------------------
meadian = 
 
3.409935352196607
------------------------------
Standard Deviation = 
 
1.4711722218106773
------------------------------
Varience = 
 
2.164347706227365


# Linear Algebra